config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :edit], param: :username
  get 'preferences', to: 'users#preferences', as: 'preferences'

  resources :fablepets, except: [:destroy, :edit], param: :unique_name do
    get 'colors'
    get 'elements'
    get 'stats'
  end

   resources :items, only: [:index, :destroy]
   get 'inventory', to: 'items#index', as: 'inventory'

   resources :item_profiles, only: [:index]
   get 'allitems', to: 'item_profiles#index', as: 'search'

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'main#index'
end

app/models/fablepet.rb
class Fablepet < ActiveRecord::Base
	self.primary_key = 'unique_name'
	belongs_to :user, foreign_key: :username


	validates :name, presence: true
	validates :unique_name, presence: true, uniqueness: true	
	validates :species, presence: true
	validates :pattern, presence: true

	serialize :all_colors, Array
	serialize :all_elements, Array

	require 'rubygems'
	require 'mini_magick'
	require 'fablepet_info_utilities'
	require 'generate_code_utilities'


	def basedir
		'public/assets/fables/bases/' + String(self.species)
	end



	def get_color (color_id)
		img = MiniMagick::Image.open('public/assets/fables/colors/' + String(color_id) + '.png')
		img.resize "750x750"
		return img
	end

	public def create_custom_pet(primary_color, secondary_color, tertiary_color, pattern, species, element)
		basedir = 'public/assets/fables/bases/' + String(species)
		element = MiniMagick::Image.open(basedir + '/element/' + String(element) + '.png')

		lines = MiniMagick::Image.open(basedir + '/lines.png')
		primary = MiniMagick::Image.open(basedir + '/patterns/' + String(pattern) + '/primary.png')
		primary = primary.composite(get_color(primary_color), 'png') do |c|
		  c.compose 'Atop'
		end

		secondary = MiniMagick::Image.open(basedir + '/patterns/' + String(pattern) + '/secondary.png')
		secondary = secondary.composite(get_color(secondary_color), 'png') do |c|
		  c.compose 'Atop'
		end

		  #tertiary = MiniMagick::Image.open(basedir + '/patterns/' + String(self.pattern) + '/tertiary.png')
		  
		  #img = tertiary.composite(secondary)
		img = secondary
		img = img.composite(primary)
		img = img.composite(lines)
		img = img.composite(element)
		return img
	end

	public def image_url
		'/assets/fables/pets/' + self.unique_name + '.png?' + self.anti_cache
	end


	
	public def update_image 
		img = create_custom_pet(self.primary_color, self.secondary_color, self.tertiary_color, self.pattern, self.species, self.curr_element)
	    img_string = self.image_url
	    img.write('public/assets/fables/pets/' + self.unique_name + '.png')
	    self.anti_cache = generate_code
	    self.save!
	    return img_string
	end

end

app/controllers/fablepets_controller.rb
class FablepetsController < ApplicationController
  before_action :set_fablepet, only: [:show, :update]
  before_action :set_fablepet_edits, only: [:colors, :elements, :stats]
  before_action :set_curr_user, only: [:show, :index, :create]
  
  require 'fablepet_info_utilities'


  # GET /fablepets
  def index
    @fablepets = Fablepet.where(:username => @curr_user.username)
  end

  # GET /fablepets/:unique_name
  def show
    @num_colors = num_colors
    @num_elements = num_elements
    @img_string = @fablepet.image_url
    @fablepet_pattern = get_pattern_name(@fablepet.pattern)
    @fablepet_species = get_species_name(@fablepet.species)
    if @curr_user
      @is_owned = @curr_user.username == @fablepet.username
    else
      @is_owned = false
    end
  end

  # GET /fablepets/new
  def new
    @fablepet = Fablepet.new
    @basic_colors = basic_colors
    @basic_species = basic_species
    @basic_elements = basic_elements
    if params[:selected_species] 
      @selected_species = params[:selected_species]
    else
      @selected_species = basic_species.sample
    end

    if params[:selected_element]
      @selected_element = params[:selected_element]
    else
      @selected_element = basic_elements.sample
    end

    if flash[:selected_primary]
      @selected_primary = params[:selected_primary]
    else
      @selected_primary = basic_colors.sample
    end


    if params[:selected_secondary]
      @selected_secondary = params[:selected_secondary]
    else
      @selected_secondary = basic_colors.sample
    end
  end


  # POST /fablepets
  def create
    @fablepet = Fablepet.new(fablepet_params)
    @fablepet.username = @curr_user.username
    @fablepet.species = params[:species]
    @fablepet.pattern = 0;
    @fablepet.curr_element = params[:element]
    @fablepet.primary_color = params[:primary_color]
    @fablepet.secondary_color = params[:secondary_color]
    @fablepet.update_image

    @fablepet.all_elements = [params[:element]]
    @fablepet.all_colors = [params[:primary_color], params[:secondary_color]]

    
      if @fablepet.save
        redirect_to @fablepet, notice: 'Fablepet was successfully created.' 
      else
        flash[:error] = @fablepet.errors
        flash[:name] = fablepet_params[:name]
        flash[:nickname] = fablepet_params[:unique_name]
        redirect_to :back
      end
    
  end

  # PATCH/PUT /fablepets/:unique_name
  def update
    respond_to do |format|
      if @fablepet.update(fablepet_params)
        @fablepet.update_image
        format.html { redirect_to @fablepet, notice: 'Updated.' }
        format.json { render :show, status: :ok, location: @fablepet }
      else
        format.html { render :show }
        format.json { render json: @fablepet.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /fablepets/:fablepet_unique_name/colors
  def colors
    @img_string = @fablepet.image_url
    @color_list = @fablepet.all_colors
    @color_selection_list = []
    @color_list.each do |i|
      color_name = get_color_name i
      @color_selection_list.append([color_name, i])
    end
  end

  # GET /fablepets/:fablepet_unique_name/elements
  def elements
    @img_string = @fablepet.image_url
    @img_string = @fablepet.image_url
    @element_list = @fablepet.all_elements
    @element_selection_list = []
    @element_list.each do |i|
      element_name = get_element_name i
      @element_selection_list.append([element_name, i])
    end
  end

  # GET /fablepets/:fablepet_unique_name/stats
  def stats
    @img_string = @fablepet.image_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.

    def set_fablepet
      @fablepet = Fablepet.find(params[:unique_name])
    end

    # GET for the editing paths because for some reason rails routes calls the name
    # param :fablepet_unique_name instead of :unique_name
    # todo: eliminate need for this??
    def set_fablepet_edits
      @fablepet = Fablepet.find(params[:fablepet_unique_name])
    end

    def set_curr_user
      @curr_user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fablepet_params
      params.require(:fablepet).permit(:name, :unique_name, :species, :pattern, :primary_color, :secondary_color, :tertiary_color, :curr_element)
    end
end

app/helpers/fablepets_helper.rb
module FablepetsHelper
end

app/views/fablepets/_colorsform.html.erb
<%= form_for(@fablepet) do |f| %>
  <% if @fablepet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fablepet.errors.count, "error") %> prohibited this Fablepet from being saved:</h2>

      <ul>
      <% @fablepet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :primary_color %><br>
    <%= f.select :primary_color, @color_selection_list %>
  </div>
  <div class="field">
    <%= f.label :secondary_color %><br>
    <%= f.select :secondary_color, @color_selection_list %>
  </div>
  <div class="field">
    <%= f.label :tertiary_color %><br>
    <%= f.select :tertiary_color, @color_selection_list%>
  </div>
  <%= hidden_field_tag(:return_to, "colors") %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fablepets/_elementsform.html.erb
<%= form_for(@fablepet) do |f| %>
  <% if @fablepet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @fablepet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :curr_element %><br>
    <%= f.select :curr_element, @element_selection_list%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fablepets/colors.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Editing Colors</h1></center>
<div class = "pet_info">
	<div class = "pet_pic">
		<%= image_tag @img_string, width: "100%", height: "100%" %>
	</div>
</div>

<div class="profile_info">
	<div class = "profile_outer_info"> 
		<font color = #ffffff size=4>Colors</font>
		<div class= "profile_inner_info">
			<center><%= render 'colorsform' %></center>
		</div>
	</div>
</div>

app/views/fablepets/edit_colors.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Colors</h1>


<div class = "pet_info">
	<div class = "pet_pic">
		<%= @img_string%>
	</div>
</div>

app/views/fablepets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fablepets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>ID</th>
      <th>Species</th>
      <th>Primary</th>
      <th>Secondary</th>
      <th>Pattern</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fablepets.each do |fablepet| %>
      <tr>
        <td><%= fablepet.name %></td>
        <td><%= fablepet.unique_name %></td>
        <td><%= fablepet.species %></td>
        <td><%= fablepet.pattern %></td>
        <td><%= fablepet.primary_color %></td>
        <td><%= fablepet.secondary_color %></td>
        <td><%= link_to 'Show', fablepet_path(fablepet.unique_name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fablepet', new_fablepet_path %>

app/views/fablepets/new.html.erb
<center><h1>Create a new Fablepet</h1></center>

<%=flash[:error] %>


<div class="petartbox">
	<center>
		<div class="petname" id="petname"></div>
		<div class="petimage" id="petimage">
			 <canvas id="pet_canvas" width="280" height="280"></canvas>
			 <canvas id="hidden_canvas" width="280" height="280" style="display:none;"></canvas>
		</div>
		<div class="petblurb" id="petblurb"></div>
	</center>
</div>

<div class="selectorbox">
<%= form_for(@fablepet) do |f| %>
	<div class="lineartselector">
		<% @basic_species.each do |i|%>
			<%if i == @selected_species %>
				<img src = <%= "/assets/fables/bases/" + String(i) + "/full.png" %> 
					width="100" 
					border="5" 
					img id= <%= String(i)%> 
					style="border-color: #3d3d3d"
				>
			<% else %>
				<img src = <%= "/assets/fables/bases/" + String(i) + "/full.png" %> 
					width="100" 
					img id= <%= String(i)%> 
					border="5" 
					style="border-color: #FFFFFF; opacity:0.4;filter:alpha(opacity=40);"
				>
			<% end %>
		<% end %>
	</div>

	<div class="colorselector">
		<h3>Primary Color</h3>
		<% @basic_colors.each do |i|%>
			<%if i == @selected_primary %>
				<img src = <%= "/assets/fables/colors/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 'p' + String(i)%> 
					border="5" 
					style="border-color: #FFFFFF"
				>
			<% else %>
				<img src = <%= "/assets/fables/colors/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 'p' + String(i)%> 
					border="5" 
					style="border-color: #3d3d3d"
				>
			<% end %>
		<% end %>
	</div>
	<div class="colorselector">
		<h3>Secondary Color</h3>
		<% @basic_colors.each do |i|%>
			<%if i == @selected_secondary %>
				<img src = <%= "/assets/fables/colors/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 's' + String(i)%> 
					border="5" 
					style="border-color: #ffffff"
				>
			<% else %>
				<img src = <%= "/assets/fables/colors/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 's' + String(i)%> 
					border="5"
					style="border-color: #3d3d3d"
				>
			<% end %>
		<% end %>
	</div>

	<div class="elementselector">
		<div id="elementname"></div>
		<% @basic_elements.each do |i|%>
			<%if i == @selected_element %>
				<img src = <%= "/assets/elements/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 'e' + String(i)%> 
				>
			<% else %>
				<img src = <%= "/assets/elements/" + String(i) + ".png"%> 
					width="30" 
					img id= <%= 'e' + String(i)%> 
					opacity = "0.4"
  					style="opacity:0.4;filter:alpha(opacity=40);"
				>
			<% end %>
		<% end %>
	</div>

	<div class="field">
	    <h3>Nickname</h3>
	    <%= f.text_field :name, value: flash[:name] %>
	</div>

	<div class="field">
		<h3>Name</h3>
		<%= f.text_field :unique_name, value: flash[:nickname] %> <input type="button" name="validifybutton" value="Verify Name" onClick="verify_name()"> 
		<div class="verify_message" id="verify_message"></div>
	</div>
  
	<%= hidden_field_tag(:species, @selected_species) %>
	<%= hidden_field_tag(:pattern, 0) %>
	<%= hidden_field_tag(:element, @selected_element) %>
	<%= hidden_field_tag(:primary_color, @selected_primary) %>
	<%= hidden_field_tag(:secondary_color, @selected_secondary) %>
	<%= f.submit 'Create Fablepet', onclick: 'submit_form()' %>
	
  <% end %>
</div>

<script>
	var selected_species = <%= @selected_species %>;
	var selected_element = <%= @selected_element %>;
	var selected_primary = <%= @selected_primary %>;
	var selected_secondary = <%= @selected_secondary %>;

	function submit_form() {
		document.getElementById("species").value = selected_species;
		document.getElementById("element").value = selected_element;
		document.getElementById("primary_color").value = selected_primary;
		document.getElementById("secondary_color").value = selected_secondary;
	}

	$(document).ready(function() {
		update_element();
    	update_species();
	});

	function verify_name() {
		var verify_message = document.getElementById("verify_message");
		var name = document.getElementById('fablepet_unique_name').value;
		if (true) {
			verify_message.innerHTML = "<font color='#0000FF'>Name '" + name +"' is valid!</font>"
		} else {
			verify_message.innerHTML = "<font color='#FF0000'>Name '" + name +"' is taken by another fablepet.</font>"
		}

	}

	function update_image() {
		var c = document.getElementById("pet_canvas");
		var c2 = document.getElementById("hidden_canvas");
		var context = c.getContext("2d");
		var context2 = c2.getContext("2d");
		var primary_color = "#FFFFFF";
		var secondary_color = "#FFFFFF";

		context.clearRect(0, 0, 280, 280);
		context2.clearRect(0, 0, 280, 280);
		$.getJSON("/assets/fables/bases/colors.json", function(json) {
			primary_color = json[selected_primary];
			secondary_color = json[selected_secondary];
			var lines = new Image();
			var primary = new Image();
			var secondary = new Image();
			var element = new Image();		
			secondary.src = "/assets/fables/bases/" + selected_species + "/patterns/0/secondary.png";
			secondary.onload = function() {
			   	context.drawImage(secondary, 0, 0, 280, 280);
			   	context.fillStyle = secondary_color;
			   	context.globalCompositeOperation = 'source-atop';
	        	context.fillRect(0,0,280,280);
	        	context.globalCompositeOperation = 'source-over';
			   	primary.src = "/assets/fables/bases/" + selected_species + "/patterns/0/primary.png";
			   	primary.onload = function() {

			   		context2.drawImage(primary, 0, 0, 280, 280);
			   		context2.fillStyle = primary_color;
			   		context2.globalCompositeOperation = 'source-atop';
			   		context2.fillRect(0,0,280,280);
			   		context2.globalCompositeOperation = 'source-over';
	    			context.drawImage(c2, 0, 0, 280, 280);

			   		lines.src = "/assets/fables/bases/" + selected_species + "/" + "/lines.png";
			   		lines.onload = function() {
			   			context.drawImage(lines, 0, 0, 280, 280);
			   			element.src = "/assets/fables/bases/" + selected_species + "/element/" + selected_element + ".png";
			   			element.onload = function() {
			   				context.drawImage(element, 0, 0, 280, 280);
						};
					};
				};
			};
		});
	}

	function update_species() {
		var namecontainer = document.getElementById("petname");
		var blurbcontainer = document.getElementById("petblurb");
		$.getJSON("/assets/fables/bases/species.json", function(json) {
			namecontainer.innerHTML = "<h1>" + json[selected_species] + "</h1>";
		});
		$.ajax({
            url : "/assets/fables/bases/" + selected_species + "/blurb.txt",
            dataType: "text",
            success : function (data) {
                blurbcontainer.innerHTML = data;
            }
        });
		update_image();
	}

	function update_element() {
		$.getJSON("/assets/fables/bases/elements.json", function(json) {
			var elecontainer = document.getElementById("elementname");
			elecontainer.innerHTML = "<h3>Element: " + json[selected_element] + "</h3>";
		});
		update_image();

	}


	<% basic_species.each do |i|%>
	$(document).on('click', '#' + <%=String(i)%>, function() { 
		<% basic_species.each do |species|%>
			var specieselement = document.getElementById(<%=species%>);
			specieselement.style.opacity = "0.4"
			specieselement.style.borderColor="#FFFFFF";
		<% end %>
		var selectedelement = document.getElementById(<%=i%>);
		selected_species = <%=i%>;
		selectedelement.style.opacity = "1.0"
		selectedelement.style.borderColor="#3d3d3d";
		update_species();
	});
	<% end %>

	<% basic_elements.each do |i|%>
	$(document).on('click', '#e' + <%= String(i)%>, function() { 
		<% basic_elements.each do |ele|%>
			document.getElementById('e' + <%=ele%>).style.opacity = "0.4"
		<% end %>
		document.getElementById('e' + <%=i%>).style.opacity = "1.0"
		selected_element  = <%=i%>;
		update_element();
	});
	<% end %>

	<% basic_colors.each do |i|%>
	$(document).on('click', '#p' + <%=i%>, function() { 
		<% basic_colors.each do |color|%>
			document.getElementById('p' + <%=color%>).style.borderColor="#3d3d3d";
		<% end %>
		document.getElementById('p' + <%=i%>).style.borderColor="#FFFFFF";
		selected_primary = <%=i%>;
		update_image();
	});

	$(document).on('click', '#s' + <%= String(i) %>, function() {
		<% basic_colors.each do |color|%>
			document.getElementById('s' + <%=color%>).style.borderColor="#3d3d3d";
		<% end %>
		document.getElementById('s' + <%=i%>).style.borderColor="#FFFFFF";
		selected_secondary = <%=i%>;
		update_image();
	});
	<% end %>
</script>

<%= link_to 'Back', fablepets_path %>

app/views/fablepets/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "pet_info">
  <div class = "pet_name">
    <center><h1><%= @fablepet.name %>: <%= @fablepet_pattern %> <%= @fablepet_species %></h1> </center>
    <font size=3>Unique Name: <%= @fablepet.unique_name %><br>
    Owned by <a href= <%=user_path(@fablepet.username) %>> <%= @fablepet.username %></a> <br></font>
  </div>
  <div class = "pet_pic">
    <img src= <%= @img_string%> width="100%", height="100%">
  </div>
  <div class = "profile_outer_info"> 
     <font color = #ffffff size=4>Personality</font>
    <div class = "profile_inner_info">
    </div>
  </div>
</div>

<div class="profile_info">
  <div class = "profile_outer_info"> 
    <font color = #ffffff size=4>Colors: <%= @fablepet.all_colors.count%> / <%= @num_colors %></font>
    <% if @is_owned %> 
      <%= link_to "Edit", fablepet_colors_path(@fablepet.unique_name)%> 
    <% end %>
    <div class = "profile_inner_info">
      <center>
        <img src = <%= "/assets/fables/colors/" + @fablepet.primary_color.to_s + ".png" %> width="50px" >
        <%if @fablepet.secondary_color != @fablepet.primary_color %>
          <img src = <%= "/assets/fables/colors/" + @fablepet.secondary_color.to_s + ".png" %> width="50px" >
        <%end %>
        <%if @fablepet.tertiary_color != @fablepet.primary_color and @fablepet.tertiary_color != @fablepet.secondary_color %>
          <img src = <%= "/assets/fables/colors/" + @fablepet.tertiary_color.to_s + ".png" %> width="50px" >
        <% end %>
        <% @fablepet.all_colors.each do |i|%>
          <%if i.to_s != @fablepet.primary_color.to_s and i.to_s != @fablepet.secondary_color.to_s and i.to_s != @fablepet.tertiary_color.to_s%>
            <img src = <%= "/assets/fables/colors/" + String(i) + ".png"%> width="50px" >
          <% end %>
        <% end %>
      </center>
    </div>
  </div>
  <div class = "profile_outer_info"> 
    <font color = #ffffff size=4>Elements: <%= @fablepet.all_elements.count%> / <%= @num_elements %></font>
    <% if @is_owned %> 
      <%= link_to "Edit", fablepet_elements_path(@fablepet.unique_name)%> 
    <% end %>
    <div class = "profile_inner_info">
      <center>
        <img src = <%= "/assets/elements/" + @fablepet.curr_element.to_s + ".png" %> width="50px" >
        <% @fablepet.all_elements.each do |i|%>
          <%if i.to_s != @fablepet.curr_element.to_s %>
            <img src = <%= "/assets/elements/" + String(i) + ".png"%> width="50px" >
          <% end %>
        <% end %>
      </center>
    </div>
  </div>
  <div class = "profile_outer_info"> 
    <font color = #ffffff size=4>Stats: <%= @fablepet.stat_total%> Points, Level <%= @fablepet.level%> </font>
    <% if @is_owned %> 
      <%= link_to "Edit", fablepet_stats_path(@fablepet.unique_name)%> 
    <% end %>
    <div class = "profile_inner_info">
      <center>
        HP: <%= @fablepet.curr_hp%> / <%= @fablepet.hp%><br>
        <canvas id="hp_bar" width="250" height="50"></canvas><br>
        ATTACK: <%= @fablepet.attack.to_i%><br>
        <canvas id="atk_bar" width="250" height="50"></canvas><br>
        DEFENSE: <%= @fablepet.defense%><br>
        <canvas id="def_bar" width="250" height="50"></canvas><br>
        MAGIC ATK: <%= @fablepet.magic_attack%><br>
        <canvas id="matk_bar" width="250" height="50"></canvas><br>
        MAGIC DEF: <%= @fablepet.magic_defense%><br>
        <canvas id="mdef_bar" width="250" height="50"></canvas><br>
        MP: <%= @fablepet.curr_mp%> / <%= @fablepet.mp%><br>
        <canvas id="mp_bar" width="250" height="50"></canvas><br>
        AGILITY: <%= @fablepet.agility%><br>
        <canvas id="agi_bar" width="250" height="50"></canvas><br>
        SPEED: <%= @fablepet.speed%><br>
        <canvas id="spd_bar" width="250" height="50"></canvas><br>
        CHARISMA: <%= @fablepet.charisma%><br>
        <canvas id="char_bar" width="250" height="50"></canvas><br>
      </center>
    </div>
  </div>
</div>

<div class="go_back"><%= link_to 'Back', fablepets_path %></div>

<script>
  window.onload = function() {   
    var colorlist = ["#0d76c0", "#0da1c0", "#13bdb7", "#278b69", 
                "#1a7738", "#228c0d", "#56a709", "#d2e500", "#e59c00", 
                "#e54600", "#c60f20", "#781636", "#540f51"]; 
    var hp_bar = document.getElementById("hp_bar");
    var ratio = <%= @fablepet.curr_hp.to_f /  @fablepet.hp.to_f%>;
    if (ratio > 1) {
      ratio = 1;
    }
    console.log(ratio);
    draw_bar(hp_bar, "#539713", "#7d4d30", ratio);
    //attack
    var atk_bar = document.getElementById("atk_bar");
    var val = <%= @fablepet.attack%>;
    var fg = get_color_out_of(colorlist.length, val);
    var bg = get_previous_out_of(colorlist.length, fg);
    draw_bar(atk_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));
    
    //defense
    var def_bar = document.getElementById("def_bar");
    val = <%= @fablepet.defense%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    draw_bar(def_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));
    
    //magic attack
    var matk_bar = document.getElementById("matk_bar");
    val = <%= @fablepet.magic_attack%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    draw_bar(matk_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));

    //magic defense
    var mdef_bar = document.getElementById("mdef_bar");
    val = <%= @fablepet.magic_defense%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    draw_bar(mdef_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));

    //mp
    var mp_bar = document.getElementById("mp_bar");
    ratio = <%= @fablepet.curr_mp.to_f /  @fablepet.mp.to_f%>;
    if (ratio > 1) {
      ratio = 1;
    }
    draw_bar(mp_bar, "#ce57a5", "#7d4d30", ratio);

    //agility
    var agi_bar = document.getElementById("agi_bar");
    val = <%= @fablepet.agility%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    draw_bar(agi_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));

    //speed
    val = <%= @fablepet.speed%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    var spd_bar = document.getElementById("spd_bar");
    draw_bar(spd_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));

    //charisma
    val = <%= @fablepet.charisma%>;
    fg = get_color_out_of(colorlist.length, val);
    bg = get_previous_out_of(colorlist.length, fg);
    var char_bar = document.getElementById("char_bar");
    draw_bar(char_bar, colorlist[fg], colorlist[bg], get_ratio(6, val));
  }

  function get_color_out_of(total, value) {
    return Math.ceil(value/6) % total;
  }

  function get_previous_out_of(total, value) {
    if (value == 0) {
      return total - 1;
    }
    return value - 1;
  }

  function get_ratio(total, value) {
    return (value % total) / total;
  }


  function draw_bar(bar, fg_color, bg_color, ratio) {
    var context = bar.getContext("2d");
    var container = new Image();
    container.src = "/assets/fables/progressbars/bar.png";
    container.onload = function() {
      context.fillStyle = bg_color;
      context.fillRect(5,5,240,40);
      context.fillStyle = fg_color;
      context.fillRect(5,5,240*ratio,40);
      context.drawImage(container, 0, 0, 250, 50);
    };
  }
</script>