config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy, :edit], param: :username
  get 'preferences', to: 'users#preferences', as: 'preferences'

  resources :fablepets, except: [:destroy, :edit], param: :unique_name do
    get 'colors'
    get 'elements'
    get 'stats'
  end

   resources :items, only: [:index, :destroy]
   get 'inventory', to: 'items#index', as: 'inventory'

   resources :item_profiles, only: [:index]
   get 'allitems', to: 'item_profiles#index', as: 'search'

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'main#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="utf-8">

  <title>FablePlay</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
  <meta name="author" content="Turese Anderson" />
  <meta name="Description" content="Virtual Pet site in progress.">
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->


</head>
<body>
<div class="header">FABLEPLAY</div>

<div class="sidebar">
  <% if current_user %>
    <div class="userprofilesidebar">
        <div class="userprofileboxsidebar">
          <div class="useravatarsidebar">
            <img src="/assets/avatars/images/0.gif">
          </div>
            <div class="userinfosidebar">
              <%= link_to current_user.username, user_path(current_user.username) %></a> <br>
              <font size=1><a href="#MONEY"> <%= current_user.fable_coins%> FC</a></font> <br>
              <font size=1><a href="#MONEY"> <%= current_user.gold_coins%> GC</a></font> <br>
              <font size=1><a href="#MONEY"> <%= current_user.opals%> Opal</a></font>
            </div>

        <center><%= link_to 'Preferences', preferences_path%> | <%= link_to 'Log Out', logout_path %></center>
      </div>
    </div>
    <% if current_user.active_pet %>
      <div class="petsidebar">
        <center>
          <img src=<%=Fablepet.find(current_user.active_pet).image_url %> width="100%">
        </center>
      </div>
    <% end %>
  <% end %>
  <div class="sidenav">
    <% if current_user %>
    <%= link_to 'Your Fablepets', fablepets_path %>
    <a href=<%= inventory_path %>>Inventory</a>
    <a href="#3">Marketplace</a>
    <% else %>
    <%= link_to 'Sign Up', signup_path %>
    <%= link_to 'Log In', login_path %>
    <% end %>
    <a href="#4">Explore</a>
    <a href="#5">News</a>
    <a href="#6">Forums</a>
  </div>
</div>

<div class="mainbody">
  <%= yield %>
</div>
   
</body>
</html> 